name: Publish Nuget Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Package Version (ex: 1.0.0)'
        required: true
        type: string

defaults:
  run:
    working-directory: ./Swappy

env:
  SL_REFERENCES_URL: https://exmod-team.github.io/SL-References/Dev.zip
  SL_REFERENCES_PATH: ${{ github.workspace }}/SCPSL/References
  SL_REFERENCES_ZIP: ${{ github.workspace }}/SCPSL/References.zip
  PACKAGE_VERSION: ${{ github.event.release.tag_name || github.event.inputs.version }}

jobs:
  push:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.0.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Pull references
      shell: pwsh
      run: |
        Write-Host "Downloading game references..."
        # Crée le dossier parent du ZIP si nécessaire
        $zipDir = Split-Path $env:SL_REFERENCES_ZIP
        if (-not (Test-Path $zipDir)) {
            New-Item -ItemType Directory -Path $zipDir | Out-Null
        }
    
        Invoke-WebRequest -Uri $env:SL_REFERENCES_URL -OutFile $env:SL_REFERENCES_ZIP -UseBasicParsing
    
        if (Test-Path $env:SL_REFERENCES_PATH) {
            Remove-Item $env:SL_REFERENCES_PATH -Recurse -Force
        }
    
        Expand-Archive -Path $env:SL_REFERENCES_ZIP -DestinationPath $env:SL_REFERENCES_PATH -Force

    - name: Restore dependencies
      run: dotnet restore

    - name: Build (Release)
      env:
        SL_REFERENCES: ${{ env.SL_REFERENCES_PATH }}
      run: dotnet build --configuration Release --no-restore -p:Version=${{ env.PACKAGE_VERSION }}
      
    - name: Upload artifact to Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ github.workspace }}/nupkg/*.nupkg
        draft: false
        
    - name: Publish to NuGet
      shell: pwsh
      run: |
        $packages = Get-ChildItem -Path "${{ github.workspace }}/nupkg" -Filter *.nupkg
        if ($packages.Count -eq 0) {
          Write-Error "No .nupkg files found in ${{ github.workspace }}/nupkg"
          exit 1
        }
        foreach ($package in $packages) {
          Write-Host "Publishing $($package.Name)..."
          dotnet nuget push $package.FullName --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        }
